"""empty message

Revision ID: 2cd2674024d9
Revises: 03f646dd0a3c
Create Date: 2025-12-01 19:25:15.248321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cd2674024d9'
down_revision = '03f646dd0a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_line1', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('street_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('street_line3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.drop_column('street_1')
        batch_op.drop_column('street_2')
        batch_op.drop_column('street_3')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('rate', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_3', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('street_2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('street_1', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('state')
        batch_op.drop_column('street_line3')
        batch_op.drop_column('street_line2')
        batch_op.drop_column('street_line1')

    # ### end Alembic commands ###
